/*
 * TaskDialog.java
 *
 * Created on 2008年2月18日, 下午2:20
 */

package com.aspire.etl.flowmonitor.dialog;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDialog;
import javax.swing.JFrame;

import com.aspire.etl.flowdefine.Task;
import com.aspire.etl.flowdefine.TaskType;
import com.aspire.etl.flowmetadata.dao.FlowMetaData;
import com.aspire.etl.tool.MQDocument;
import com.aspire.etl.tool.Utils;

/**
 * 
 * @author x_lixin_a
 * 
 * luoqi 2008-3-22 修改：动态加载任务动态参数对话框
 * 
 */
public class TaskDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

	public TaskDialog(JFrame parent) {
		super(parent, true);

		this.parentFrame = parent;
		initComponents();

		this.setTitle("任务配置对话框");
	}

	public void loadValue(Task task) {
		try {
			this.task = task;
			TaskType taskType = FlowMetaData.getInstance().queryTaskType(
					task.getTaskType());
			this.attributeMap = FlowMetaData.getInstance()
					.queryTaskAttributeMap(task.getTaskID());
			String taskTypeDesc = null;
			if (taskType != null) {
				taskTypeDesc = taskType.getDescription();
			}

			MQDocument mqDoc = new MQDocument();
			mqDoc.setCharLimit("[^\u4e00-\u9fa5]");
			this.taskTypeL.setText("任务类型：" + taskTypeDesc);
			this.NameTF.setDocument(mqDoc);
			this.NameTF.setText(task.getTask());
			this.AlertsourceIDTF.setText(task.getAlertID());
			this.PerformanceidTF.setText(task.getPerformanceID());
			this.DescriptionTF.setText(task.getDescription());
			this.PlantimeTF.setText(String.valueOf(task.getPlantime()));

			if (task.getIsRoot() == 1) {
				this.isRootCB.setSelected(true);
			} else {
				this.isRootCB.setSelected(false);
			}

			if (task.getSuspend() == 1) {
				this.isSuspendedCB.setSelected(true);
			} else {
				this.isSuspendedCB.setSelected(false);
			}

			if (task.getStatus() == 0) {
				this.statusLValue.setText("READY");
			} else if (task.getStatus() == 1) {
				this.statusLValue.setText("RUNNING");
			} else if (task.getStatus() == 2) {
				this.statusLValue.setText("SUCCESSED");
			} else if (task.getStatus() == -1) {
				this.statusLValue.setText("FAILED");
			}
		} catch (Exception ex) {
			Logger.getLogger(TaskDialog.class.getName()).log(Level.SEVERE,
					null, ex);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        DescriptionL = new javax.swing.JLabel();
        DescriptionTF = new javax.swing.JTextField();
        PlantimeL = new javax.swing.JLabel();
        PlantimeTF = new javax.swing.JTextField();
        AlertsourceIDL = new javax.swing.JLabel();
        AlertsourceIDTF = new javax.swing.JTextField();
        PerformanceidL = new javax.swing.JLabel();
        PerformanceidTF = new javax.swing.JTextField();
        isRootL = new javax.swing.JLabel();
        isRootCB = new javax.swing.JCheckBox();
        taskTypeL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        isSynInputCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        isSuspendedL = new javax.swing.JLabel();
        isSuspendedCB = new javax.swing.JCheckBox();
        statusL = new javax.swing.JLabel();
        statusLValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("\u4efb\u52a1\u4fe1\u606f"));
        NameL.setText("\u4efb\u52a1\u540d\uff1a");

        NameTF.setToolTipText("\u4efb\u52a1\u540d,\u4e0d\u53ef\u4ee5\u8f93\u5165\u4e2d\u6587");
        NameTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NameTFCaretUpdate(evt);
            }
        });

        DescriptionL.setText("\u63cf\u8ff0\uff1a");

        DescriptionTF.setToolTipText("\u63cf\u8ff0");

        PlantimeL.setText("\u6240\u9700\u65f6\u95f4\uff1a");

        PlantimeTF.setToolTipText("\u9884\u8ba1\u8fd0\u884c\u6240\u9700\u65f6\u95f4   \u7cbe\u786e\u5230 \u5206\u949f");

        AlertsourceIDL.setText("\u544a\u8b66ID\uff1a");

        AlertsourceIDTF.setToolTipText("\u544a\u8b66ID");

        PerformanceidL.setText("\u6027\u80fdID\uff1a");

        PerformanceidTF.setToolTipText("\u6027\u80fdID");

        isRootL.setText("\u662f\u5426\u662f\u6839\u8282\u70b9\uff1a");

        isRootCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        isRootCB.setEnabled(false);
        isRootCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        taskTypeL.setText("\u4efb\u52a1\u7c7b\u578b\uff1a");

        jLabel3.setText("\u5728\u4fdd\u5b58\u4e4b\u524d\u8bf7\u586b\u5199\u52a8\u6001\u53c2\u6570");

        jButton3.setText("\u52a8\u6001\u53c2\u6570...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        isSynInputCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSynInputCBActionPerformed(evt);
            }
        });

        jLabel1.setText("\u662f\u5426\u8fdb\u884c\u540c\u6b65\u8f93\u5165\uff1a");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PlantimeL)
                                    .add(NameL)
                                    .add(PerformanceidL)
                                    .add(DescriptionL)
                                    .add(AlertsourceIDL))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(PlantimeTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(isRootL)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(isRootCB))
                                    .add(AlertsourceIDTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .add(PerformanceidTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .add(DescriptionTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .add(NameTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton3)))
                        .addContainerGap())
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(taskTypeL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 94, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(isSynInputCB)
                        .add(120, 120, 120))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(taskTypeL)
                    .add(isSynInputCB)
                    .add(jLabel1))
                .add(5, 5, 5)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NameL)
                    .add(NameTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AlertsourceIDTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AlertsourceIDL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PerformanceidL)
                    .add(PerformanceidTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DescriptionTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(DescriptionL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PlantimeL)
                    .add(PlantimeTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(isRootL)
                    .add(isRootCB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jButton3)))
        );

        jButton1.setText("\u4fdd\u5b58");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("\u53d6\u6d88");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("\u6700\u8fd1\u4e00\u6b21\u8fd0\u884c\u4fe1\u606f"));
        isSuspendedL.setText("\u662f\u5426\u6302\u8d77\uff1a");

        isSuspendedCB.setToolTipText("\u662f\u5426\u6302\u8d77");
        isSuspendedCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        isSuspendedCB.setMargin(new java.awt.Insets(0, 0, 0, 0));

        statusL.setText("\u8fd0\u884c\u72b6\u6001\uff1a");

        statusLValue.setText("12");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(isSuspendedL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(isSuspendedCB)
                .add(32, 32, 32)
                .add(statusL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLValue)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(isSuspendedL)
                    .add(isSuspendedCB)
                    .add(statusL)
                    .add(statusLValue)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton1)
                        .add(40, 40, 40)
                        .add(jButton2)
                        .add(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void NameTFCaretUpdate(javax.swing.event.CaretEvent evt) {// GEN-FIRST:event_NameTFCaretUpdate
		// TODO 将在此处添加您的处理代码：
		if (isSynInput) {
			this.AlertsourceIDTF.setText(this.NameTF.getText());
			this.PerformanceidTF.setText(this.NameTF.getText());
		}
	}// GEN-LAST:event_NameTFCaretUpdate

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.task.setTask(this.NameTF.getText());
		this.task.setAlertID(this.AlertsourceIDTF.getText());
		this.task.setPerformanceID(this.PerformanceidTF.getText());
		this.task.setDescription(this.DescriptionTF.getText());
		this.task.setPlantime(Integer.parseInt(this.PlantimeTF.getText()));

		if (this.isSuspendedCB.isSelected()) {
			task.setSuspend(1);
		} else {
			task.setSuspend(0);
		}
		this.setIsConfirm(true);
		this.setVisible(false);

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:

		String taskTypeName = task.getTaskType();
		TaskType taskType = null;
		FlowMetaData flowMetaData = null;
		
		// 根据不同的任务类型打开不同的任务参数配置窗口
		JDialog paramDialog = null;
		String className = null;
		String desingerPluginDir = null;

		try {
			flowMetaData = FlowMetaData.getInstance();
			taskType = flowMetaData.queryTaskType(taskTypeName);
			className = taskType.getDesignerPlugin();
			
//			desingerPluginDir = flowMetaData
//					.querySysConfigValue("SYS_DESIGNER_PLUGIN_DIR");
			
			desingerPluginDir = taskType.getDesignerPluginJar();

			Class dialogClass = Utils.loadClassByName(desingerPluginDir,
					className);

			Constructor cDialogConstructor = dialogClass
					.getConstructor(new Class[] { java.awt.Frame.class });
			paramDialog = (JDialog) cDialogConstructor
					.newInstance(new Object[] { parentFrame });

			Method mLoadValue = dialogClass.getMethod("loadValue",
					new Class[] { java.util.Map.class });
			mLoadValue.invoke(paramDialog, new Object[] { attributeMap });

			paramDialog.setLocationRelativeTo(null);
			paramDialog.setVisible(true);
			
			FlowMetaData.getInstance().insertTaskAttributeMap(task.getTaskID(),
					attributeMap);

			

		} catch (MalformedURLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (ClassNotFoundException e1) {
			System.out.println("从目录"+desingerPluginDir+" 加载"+className+"失败！");	
			e1.printStackTrace();
		} catch (InstantiationException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (IllegalAccessException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	
	
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void isSynInputCBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_isSynInputCBActionPerformed
		// TODO add your handling code here:
		if (this.isSynInputCB.isSelected()) {
			this.isSynInput = true;
		} else {
			this.isSynInput = false;
		}
	}// GEN-LAST:event_isSynInputCBActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				javax.swing.JFrame aframe = new javax.swing.JFrame();
				// Task task = new Task(new String("任务流名字"),new
				// String("任务名"),new String("auditor"),1,1,1,1,new
				// String("描述"),new String("性能id"),new String("告警id"),20,30);
				TaskDialog dialog = new TaskDialog(aframe);
				dialog.loadValue(new Task());
				// dialog.loadValue(task);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // 变量声明 - 不进行修改//GEN-BEGIN:variables
    private javax.swing.JLabel AlertsourceIDL;
    private javax.swing.JTextField AlertsourceIDTF;
    private javax.swing.JLabel DescriptionL;
    private javax.swing.JTextField DescriptionTF;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel PerformanceidL;
    private javax.swing.JTextField PerformanceidTF;
    private javax.swing.JLabel PlantimeL;
    private javax.swing.JTextField PlantimeTF;
    private javax.swing.JCheckBox isRootCB;
    private javax.swing.JLabel isRootL;
    private javax.swing.JCheckBox isSuspendedCB;
    private javax.swing.JLabel isSuspendedL;
    private javax.swing.JCheckBox isSynInputCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel statusL;
    private javax.swing.JLabel statusLValue;
    private javax.swing.JLabel taskTypeL;
    // 变量声明结束//GEN-END:variables
	private JFrame parentFrame;

	private Task task;

	private Map<String, String> attributeMap;

	private boolean isSynInput = false;

	private boolean isConfirm = false;

	public boolean isIsConfirm() {
		return isConfirm;
	}

	public void setIsConfirm(boolean isConfirm) {
		this.isConfirm = isConfirm;
	}

	public Map getMap() {
		return attributeMap;
	}

	public void setMap(Map<String, String> map) {
		this.attributeMap = map;
	}

	public Task getTask() {
		return task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

}
